accounts/urls.py
from django.urls import path,include
from accounts import views
from django.contrib.auth import views as auth_views 

app_name= "accounts"

urlpatterns = [
    path('signup/',views.SignUp.as_view(),name="signup"),
    path('login/',auth_views.LoginView.as_view(template_name="accounts/login.html"), name = "login"),
    path('logout/',auth_views.LogoutView.as_view(), name = "logout"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomeView.as_view(),name="home"),
    path('text/',views.TextView.as_view(),name="text"),
    path('thanks/',views.ThanksView.as_view(),name="thanks"),
    path('accounts/',include("accounts.urls",namespace="accounts")),
    path('accounts/',include("django.contrib.auth.urls")),
    path('posts/', include("posts.urls", namespace="posts")),
    path('groups/',include("groups.urls", namespace="groups")),
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("new/<slug>", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% load static %}
  <link rel="stylesheet" href="{% static 'accounts/css/bootstrap.css'%}">
  <link rel="stylesheet" href="{% static 'blog/master.css'%}">
  <title>Home</title>
</head>
<body>
   <nav class="navbar navbar-expand-lg mynav" role="navigation" id="navbar">
      <div class=" container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
        </div>
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link mynav" class="btn btn-simple" href="{% url 'home' %}">Home</a>
          <a class="nav-item nav-link mynav" class="btn btn-simple" href="{% url 'admin:index' %}">Admin</a>
          <a class="nav-item nav-link mynav" class="btn btn-simple" href="{% url 'groups:all' %}">Groups</a>
          {% if user.is_authenticated %}
            <a class="nav-item nav-link mynav" class="btn btn-simple" href="{% url 'posts:all' %}">Activity</a>
            <a class="nav-item nav-link mynav" class="btn btn-simple" href="{% url 'posts:create' %}">Post</a>
            <a class="nav-item nav-link mynav" class="btn btn-simple" href="{% url 'groups:create' %}">Create Groups</a>
            <a class="nav-item nav-link mynav" class="btn btn-simple" href="{% url 'accounts:logout' %}">Logout</a>
          {% else %}
          <a class="nav-item nav-link mynav" class="btn btn-simple" href="{% url 'accounts:login' %}">Login</a>
          <a class="nav-item nav-link mynav" class="btn btn-simple" href="{% url 'accounts:signup' %}">Signup</a>
          {% endif %}
        </div>
      </div>
    </nav>
  </div>
  <div class="container">
    <div class="jumbotron bg-dark img-fluid">
      Hey there bud!!
    </div>
  {% block body_block %}
    
    {% endblock %}
    <footer>
      Social
    </footer>
  <!-- Scripts -->
  <script src="{% static 'accounts/js/jquery.js' %}" ></script>
  <script src="{% static 'accounts/js/bootstrap.min.js' %} "></script>
  <script src="{% static 'accounts/js/bootstrap.bundle.js'%}"></script>
</body>
</html>

templates/text.html
{% extends "index.html" %}
{% load static %}
{% block body_block %}
<div class="container">
    You logged in!!
</div>
{% endblock %}

templates/thanks.html
{% extends "index.html" %}
{% load static %}
{% block body_block %}
<div class="container">
    <h1>Thanks</h1>
</div>
{% endblock %}